version: '3.8'

services:
  app:
    build: .
    container_name: golang-app
    depends_on:
      - mongo
    environment:
      - PORT=8000
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
    ports:
      - "8000:8000"
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
